### ISSUE TITLE
mix test hangs indefinitely

### ISSUE THREAD

**Issue by elbow-jason** [FarmBot-Labs/laughing-octo-telegram#1]
```

elbow-jason@Jasons-MacBook-Pro-18424 ~/W/e/laughing-octo-telegram (elbow-jason/init-review) [1]> mix test
Compiling 1 file (.ex)

01:37:47.587 [debug] Starting Firmware on Target: rpi3

01:37:47.603 [debug] Starting Network

01:37:47.604 [debug] HOSTAPD STUB

01:37:47.604 [debug] HOSTAPD STUB

01:37:47.604 [debug] Starting Controller

01:37:47.622 [debug] MQTT INIT

```

**Comment by ConnorRigby** [comment]
@elbow-jason this should actually be fixed now. 
I haven't written very many tests, and they require to be ran as `mix test --no-start`.
The hanging on MQTT INIT is because it is waiting for credentials via an http post to the embedded cowboy server. This is for Wifi Configuration and what not for the Farmbot. Less than ideal for development and test environments but i haven't got around to fixing this yet.

**Comment by elbow-jason** [comment]
It works! Thanks.
